apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-gpu-app
spec:
  maxReplicas: 4 # Update this according to your desired number of replicas
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: my-gpu-app
  metrics:
  - type: Pods
    pods:
      metric:
        name: DCGM_FI_DEV_GPU_UTIL
      target:
        type: AverageValue
        averageValue: 40